name: Fast APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm install -g eas-cli
      - run: mkdir -p apk-output
      - name: EAS Login
        run: eas login --non-interactive --token ${{ secrets.EAS_TOKEN }}
      - name: Build APK
        run: eas build --platform android --output=apk-output/
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: apk-output/*.apk
